baseURL: "https://blog.javivela.dev/"
title: "Javi Vela Blog"
paginate: 8
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
defaultContentLanguage: "es"
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  languages:
    es:
      languageName: "Español"
      languageAltTitle: Español
      weight: 2
      menu:
        main:
          - name: Posts
            url: posts/
            weight: 1
          - name: Buscar
            url: search/
            weight: 10
          - name: Etiquetas
            url: tags/
            weight: 10

  librecounter:
    enabled: true

  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  # description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  # author: Theme PaperMod
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: ["twitter", "linkedin"]
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  # comments: false
  images: ["papermod-cover.png"]

  profileMode:
    enabled: true
    title: Javi Vela Blog
    subtitle: "Soy arquitecto de soluciones y un apasionado de las tecnologías cloud y tecnologías microsoft. Este es mi sitio web para hablar sobre Devops, Azure, AWS, CI/CD, K8S, contenedores y arquitectura."
    imageUrl: "JavierVela.jpg"
    imageTitle: "Javi Vela fotografía"
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: Posts
        url: posts/

  homeInfoParams:
    Title: Javi Vela Blog
    Content: "Soy arquitecto de soluciones y un apasionado de las tecnologías cloud y tecnologías microsoft. Este es mi sitio web para hablar sobre Devops, Azure, AWS, CI/CD, K8S, contenedores y arquitectura."

  socialIcons:
    - name: github
      url: "https://github.com/fjvela"
    - name: twitter
      url: "https://twitter.com/jvela"
    - name: linkedin
      url: "https://www.linkedin.com/in/javiervelaaylon/"
    - name: RsS
      url: "index.xml"

  # editPost:
  #   URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # label:
  #   text: "Home"
  #   icon: icon.png
  #   iconHeight: 35

  analytics:
    google:
      SiteVerificationTag: Z9k5TW79n5H64zWLwEcNkbNITNDDepKoE2udZjirxXM
    bing:
      SiteVerificationTag: 6A293DF736526A40A24D911811A73F7D

  # assets:
  #   favicon: "<link / abs url>"
  #   favicon16x16: "<link / abs url>"
  #   favicon32x32: "<link / abs url>"
  #   apple_touch_icon: "<link / abs url>"
  #   safari_pinned_tab: "<link / abs url>"

  # cover:
  #   hidden: true # hide everywhere but not in structured data
  #   hiddenInList: true # hide on list pages and home
  #   hiddenInSingle: true # hide on single page

  # fuseOpts:
  #   isCaseSensitive: false
  #   shouldSort: true
  #   location: 0
  #   distance: 1000
  #   threshold: 0.4
  #   minMatchCharLength: 0
  #   keys: ["title", "permalink", "summary", "content"]

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
#   highlight:
#     # anchorLineNos: true
#     codeFences: true
#     guessSyntax: true
#     lineNos: true
#     # noClasses: false
#     style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
